$:
  vscode:
    - docker:
        image:
          name: docker.cnb.cool/examples/workspace-images/workspace-node:22
          # 使用 CI 构建时默认注入的环境变量
          dockerUser: $CNB_TOKEN_USER_NAME
          dockerPassword: $CNB_TOKEN
      runner:
        cpus: 8
      env:
        CNB_WELCOME_EXECUTE_COMMAND: pnpm preview
      services:
        - vscode
        - docker

  push:
    # 从私有仓库导入环境变量：
    # 参考：https://docs.cnb.cool/en/build/env.html#importing-environment-variables
    - runner:
        cpus: 8
      imports: https://cnb.cool/aii.mobi/envs/-/blob/main/edgeone-pages-token.yml
      stages:
        # 构建当前项目
        - name: 云原生构建生成并部署网站
          image: docker.cnb.cool/examples/workspace-images/workspace-node:22
          jobs:
          - name: 构建构建网站文件
            script: pnpm stage1
          - name: 发布到Edgeone Pages中部署
            script: node_modules/.bin/edgeone pages deploy ./out --name cnb-issue-sites --token $EDGEONE_PAGES_API_TOKEN

main:
  "crontab: 0 */1 * * *":
  # 定时任务:每小时执行一次
    - runner:
        cpus: 8
      imports: https://cnb.cool/aii.mobi/envs/-/blob/main/edgeone-pages-token.yml
      stages:
        # 构建当前项目
        - name: 云原生构建生成并部署网站
          image: docker.cnb.cool/examples/workspace-images/workspace-node:22
          jobs:
          - name: 构建构建网站文件
            script: pnpm stage1
          - name: 发布到Edgeone Pages中部署
            script: node_modules/.bin/edgeone pages deploy ./out --name cnb-issue-sites --token $EDGEONE_PAGES_API_TOKEN

  web_trigger:
    - runner:
        cpus: 8
      imports: https://cnb.cool/aii.mobi/envs/-/blob/main/edgeone-pages-token.yml
      stages:
        # 构建当前项目
        - name: 云原生构建生成并部署网站
          image: docker.cnb.cool/examples/workspace-images/workspace-node:22
          jobs:
          - name: 构建构建网站文件
            script: pnpm stage1
          - name: 发布到Edgeone Pages中部署
            script: node_modules/.bin/edgeone pages deploy ./out --name cnb-issue-sites --token $EDGEONE_PAGES_API_TOKEN

# 其它多种自动触发构建的方式增加中...